---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
unzip('activity.zip')
data <- read.csv('activity.csv')
data$date <- as.Date(data$date)

```
## What is mean total number of steps taken per day?

```{r}
library(dplyr)
library(ggplot2)
total_steps_days <-data %>% group_by(date) %>% summarise(sum = sum(steps,na.rm = T));
qplot(total_steps_days$sum,geom = 'histogram')
```


### mean
```{r}

mean(total_steps_days$sum,na.rm = T)


```

### median
```{r}
median(total_steps_days$sum)

```
## What is the average daily activity pattern?
```{r}

avg_steps_interval <- data %>% group_by(interval) %>% summarise(avg_steps = mean(steps,na.rm=T));
plot(x = avg_steps_interval$interval,y= avg_steps_interval$avg_steps,type='l',ylab = 'Average steps',xlab='interval' )
```
```{r}

avg_steps_interval[which(avg_steps_interval$avg_steps== max(avg_steps_interval$avg_steps)),'interval']

```

## Imputing missing values
i will replace the na values with the mean for it's  interval 
```{r}
nomis <- sum(is.na(data$steps))
sprintf('number of missing values %s',nomis)
newdata <- data %>% group_by(interval) %>% summarise(avg = mean(steps,na.rm=T),steps,date);
newdata$steps <- ifelse(is.na(newdata$steps),newdata$avg,newdata$steps);

```
```{r}
new_total_steps_days <-newdata %>% group_by(date) %>% summarise(sum = sum(steps,na.rm = T))
qplot(x = new_total_steps_days$sum,type='histogram')

```


### Mean
```{r}

mean(new_total_steps_days$sum)
```
### Median
```{r}
median(new_total_steps_days$sum)
```
both mean and median increased
## Are there differences in activity patterns between weekdays and weekends?
```{r}
weekends<-weekdays(data$date) %in% c('Saturday','Sunday')
data$weekends <- factor(weekends,label=c('weekdays','weekends'))
avg_steps_interval_weekends <- data %>% group_by(interval,weekends) %>% summarise(avg_steps = mean(steps,na.rm=T))
ggplot(data= avg_steps_interval_weekends,aes(x = interval,y=avg_steps))+geom_path()+facet_grid(weekends~.)


```


